/**
 * test_dxf_import_logger.cpp — Tests DxfImportLogger logging module
 *
 * Covers:
 *   LoggerRegistry  — create / drop / singleton
 *   NullSafety      — All functions safe with nullptr logger
 *   DataLogging     — logRawDxfData / logConvertedSamData output validation
 *   ErrorReporting  — reportImportError dual-channel write
 *   LogFormat       — Timestamp / level / import tag / key-value format
 */
#include <gtest/gtest.h>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>
#include <chrono>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <cmath>

#include "DxfImportRuntime.h"
#include "DxfData.h"
#include "SketchConversion.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// ============================================================================
// Helper functions
// ============================================================================

static std::string readFileContent(const QString& path)
{
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return {};
    QTextStream in(&f);
    return in.readAll().toStdString();
}

static QString perImportLogPath(const std::string& importId)
{
    return QCoreApplication::applicationDirPath()
           + "/logs/imports/dxf_import_" + QString::fromStdString(importId) + ".log";
}

static QString errorLogPath()
{
    return QCoreApplication::applicationDirPath()
           + "/logs/dxf_import_errors.log";
}

// Use a unique suffix to avoid log file conflicts between test runs
static std::string uniqueSuffix()
{
    auto now = std::chrono::steady_clock::now().time_since_epoch();
    return std::to_string(now.count());
}

// ============================================================================
// Test fixture — manages importId and temporary log cleanup
// ============================================================================

class DxfImportLoggerTest : public ::testing::Test {
protected:
    void SetUp() override
    {
        suffix = uniqueSuffix();
        importId = "test_" + suffix;
    }

    void TearDown() override
    {
        dropDxfImportLogger(importId);
        // Remove log files generated by this test
        QFile::remove(perImportLogPath(importId));
    }

    std::string suffix;
    std::string importId;
};

// ============================================================================
// Group 1: LoggerRegistryTest — Logger registry management
// ============================================================================

TEST_F(DxfImportLoggerTest, create_import_logger_returns_valid)
{
    auto logger = createDxfImportLogger(importId);
    ASSERT_NE(logger, nullptr);
    EXPECT_EQ(logger->name(), "dxf_import_" + importId);
}

TEST_F(DxfImportLoggerTest, error_logger_is_singleton)
{
    auto e1 = dxfErrorLogger();
    auto e2 = dxfErrorLogger();
    ASSERT_NE(e1, nullptr);
    EXPECT_EQ(e1.get(), e2.get());
}

TEST_F(DxfImportLoggerTest, drop_removes_from_registry)
{
    {
        auto logger = createDxfImportLogger(importId);
        ASSERT_NE(logger, nullptr);
    }
    dropDxfImportLogger(importId);
    EXPECT_EQ(spdlog::get("dxf_import_" + importId), nullptr);
}

TEST(DxfImportSessionTest, preservesUnicodePathAndFinishesOnce)
{
    const QString filePath = QString::fromUtf8("C:/测试/图纸.dxf");
    DxfImportSession session(filePath, 1.0, 2.0, 3.0, 0.1, 100000);

    ASSERT_NE(session.logger(), nullptr);
    EXPECT_EQ(session.pathText(), filePath.toUtf8().toStdString());
    EXPECT_GE(session.elapsed(), 0);

    const std::string importId = session.importId();
    const QString logPath = perImportLogPath(importId);
    std::weak_ptr<spdlog::logger> loggerLifetime = session.logger();
    session.finish();
    EXPECT_EQ(session.logger(), nullptr);
    EXPECT_TRUE(loggerLifetime.expired());
    EXPECT_EQ(spdlog::get("dxf_import_" + importId), nullptr);
    EXPECT_NO_THROW(session.finish());

    const std::string content = readFileContent(logPath);
    EXPECT_NE(content.find("started file="), std::string::npos) << content;
    QFile::remove(logPath);
}

TEST(DxfImportSessionTest, scopeExitFinishesAndReleasesLogger)
{
    std::weak_ptr<spdlog::logger> loggerLifetime;
    QString logPath;
    {
        DxfImportSession session(
            QStringLiteral("C:/scope-exit.dxf"),
            0.0, 0.0, 0.0, 0.01, 100000);
        ASSERT_NE(session.logger(), nullptr);
        loggerLifetime = session.logger();
        logPath = perImportLogPath(session.importId());
    }

    EXPECT_TRUE(loggerLifetime.expired());
    const std::string content = readFileContent(logPath);
    EXPECT_NE(content.find("started file="), std::string::npos) << content;
    QFile::remove(logPath);
}

// ============================================================================
// Group 2: NullSafetyTest — Null pointer safety
// ============================================================================

TEST_F(DxfImportLoggerTest, log_raw_dxf_data_null_logger)
{
    DxfData data;
    data.addPoint(DxfPoint(1.0, 2.0, 3.0));
    EXPECT_NO_THROW(logRawDxfData(nullptr, importId, data));
}

TEST_F(DxfImportLoggerTest, log_converted_sam_data_null_logger)
{
    SamData data;
    data.addLine(DxfLine(DxfPoint(0, 0, 0), DxfPoint(1, 1, 1)));
    EXPECT_NO_THROW(logConvertedSamData(nullptr, importId, data));
}

TEST_F(DxfImportLoggerTest, report_import_error_null_loggers)
{
    EXPECT_NO_THROW(
        reportImportError(nullptr, nullptr, importId, "test.dxf",
                          "parse", " error=\"fail\"", 42));
}

TEST_F(DxfImportLoggerTest, report_import_error_null_per_import_logger)
{
    auto errorLogger = dxfErrorLogger();
    ASSERT_NE(errorLogger, nullptr);
    EXPECT_NO_THROW(
        reportImportError(nullptr, errorLogger, importId, "test.dxf",
                          "parse", " error=\"fail\"", 42));
}

// ============================================================================
// Group 3: DataLoggingTest — Entity data logging
// ============================================================================

TEST_F(DxfImportLoggerTest, log_raw_dxf_data_all_entities)
{
    auto logger = createDxfImportLogger(importId);
    ASSERT_NE(logger, nullptr);

    DxfData data;
    data.addPoint(DxfPoint(1.0, 2.0, 3.0));
    data.addLine(DxfLine(DxfPoint(0, 0, 0), DxfPoint(10, 20, 0)));
    data.addCircle(DxfCircle(DxfPoint(5, 5, 0), 3.0));
    data.addArc(DxfArc(DxfPoint(0, 0, 0), 1.0, 0.0, M_PI, true));
    {
        std::vector<DxfPoint> verts = { DxfPoint(0, 0, 0), DxfPoint(1, 1, 0) };
        std::vector<double> bulges = { 0.5 };
        data.addLWPolyline(DxfLWPolyline(verts, bulges, false, 0.0));
    }
    {
        DxfEllipse e(DxfPoint(0, 0, 0), DxfPoint(2, 0, 0), 0.5, 0.0, M_PI, true);
        data.addEllipse(e);
    }

    logRawDxfData(logger, importId, data);
    logger->flush();

    std::string content = readFileContent(perImportLogPath(importId));

    EXPECT_NE(content.find("raw POINT"), std::string::npos)   << content;
    EXPECT_NE(content.find("raw LINE"), std::string::npos)    << content;
    EXPECT_NE(content.find("raw CIRCLE"), std::string::npos)  << content;
    EXPECT_NE(content.find("raw ARC"), std::string::npos)     << content;
    EXPECT_NE(content.find("raw LWPOLYLINE"), std::string::npos) << content;
    EXPECT_NE(content.find("raw ELLIPSE"), std::string::npos) << content;
    EXPECT_NE(content.find("position=(1, 2, 3)"), std::string::npos);
}

TEST_F(DxfImportLoggerTest, log_converted_sam_data_lines)
{
    auto logger = createDxfImportLogger(importId);
    ASSERT_NE(logger, nullptr);

    SamData data;
    data.addLine(DxfLine(DxfPoint(10, 20, 0), DxfPoint(30, 40, 0)));
    data.addCircle(DxfCircle(DxfPoint(50, 60, 0), 5.0));

    logConvertedSamData(logger, importId, data);
    logger->flush();

    std::string content = readFileContent(perImportLogPath(importId));

    EXPECT_NE(content.find("converted LINE"), std::string::npos)   << content;
    EXPECT_NE(content.find("converted CIRCLE"), std::string::npos) << content;
    EXPECT_NE(content.find("start=(10, 20, 0)"), std::string::npos);
    EXPECT_NE(content.find("end=(30, 40, 0)"), std::string::npos);
}

// ============================================================================
// Group 4: ErrorReportingTest — Error reporting
// ============================================================================

TEST_F(DxfImportLoggerTest, report_import_error_writes_to_both)
{
    auto logger = createDxfImportLogger(importId);
    auto errLogger = dxfErrorLogger();
    ASSERT_NE(logger, nullptr);
    ASSERT_NE(errLogger, nullptr);

    reportImportError(logger, errLogger, importId,
                      "C:\\fake.dxf", "parse",
                      " error=\"bad entity\"", 123);

    logger->flush();
    errLogger->flush();

    std::string perLog = readFileContent(perImportLogPath(importId));
    std::string errLog = readFileContent(errorLogPath());

    EXPECT_NE(perLog.find("parse_failed"), std::string::npos) << perLog;
    EXPECT_NE(perLog.find("bad entity"), std::string::npos)   << perLog;
    EXPECT_NE(perLog.find("elapsed_ms=123"), std::string::npos) << perLog;

    EXPECT_NE(errLog.find("parse_failed"), std::string::npos)  << errLog;
    EXPECT_NE(errLog.find("bad entity"), std::string::npos)    << errLog;
}

TEST_F(DxfImportLoggerTest, error_logger_has_file_field)
{
    auto logger = createDxfImportLogger(importId);
    auto errLogger = dxfErrorLogger();
    ASSERT_NE(errLogger, nullptr);

    reportImportError(logger, errLogger, importId,
                      "C:\\fake.dxf", "parse",
                      " error=\"bad\"", 0);
    errLogger->flush();

    std::string errLog = readFileContent(errorLogPath());
    EXPECT_NE(errLog.find("file=\""), std::string::npos) << errLog;
}

TEST_F(DxfImportLoggerTest, per_import_logger_no_file_field)
{
    auto logger = createDxfImportLogger(importId);
    auto errLogger = dxfErrorLogger();
    ASSERT_NE(logger, nullptr);

    reportImportError(logger, errLogger, importId,
                      "C:\\fake.dxf", "conversion",
                      " error=\"oops\"", 0);
    logger->flush();

    std::string perLog = readFileContent(perImportLogPath(importId));
    // Per-import log should not contain file= field
    EXPECT_EQ(perLog.find("file=\""), std::string::npos) << perLog;
}

// ============================================================================
// Group 5: LogFormatTest — Log format
// ============================================================================

TEST_F(DxfImportLoggerTest, info_log_contains_import_tag)
{
    auto logger = createDxfImportLogger(importId);
    ASSERT_NE(logger, nullptr);

    logger->info("[import={}] started file=\"test.dxf\" base=(0, 0, 0)",
                 importId);
    logger->flush();

    std::string content = readFileContent(perImportLogPath(importId));
    EXPECT_NE(content.find("[import=" + importId + "]"), std::string::npos);
    EXPECT_NE(content.find("[info]"), std::string::npos);
}

TEST_F(DxfImportLoggerTest, error_log_contains_stage)
{
    auto logger = createDxfImportLogger(importId);
    auto errLogger = dxfErrorLogger();
    ASSERT_NE(logger, nullptr);

    reportImportError(logger, errLogger, importId,
                      "test.dxf", "commit",
                      " sketch=\"S1\" submitted=5 error=\"OOM\"", 250);
    logger->flush();

    std::string content = readFileContent(perImportLogPath(importId));
    EXPECT_NE(content.find("commit_failed"), std::string::npos) << content;
    EXPECT_NE(content.find("sketch=\"S1\""), std::string::npos) << content;
    EXPECT_NE(content.find("elapsed_ms=250"), std::string::npos) << content;
}

// ============================================================================
// main — Provides QCoreApplication for the logging module
// ============================================================================

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
